# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.
os: linux

language: node_js

node_js:
  - 12
cache:
  - npm
  - pip

jobs:
  include:
    - stage: Test
      before_script:
        - sudo add-apt-repository -y ppa:freecad-maintainers/freecad-stable
        - sudo apt-get update
        - sudo apt-get install -y freecad freecad-python3

      script:
        # - ls -l /usr/lib/freecad-python3/lib
        - sudo mkdir /usr/lib/freecad-python3/Mod
        # - python3 .travis/freecad_open_test.py common_parts.FCStd
        - for i in $(ls -1 *.FCStd); do python3 ./.travis/freecad_open_test.py $i; done

stages:
  - Test
  - Merge

import:
  - credentials.yml
  - travis-merger.yml
