# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# jobs:
#   include:
#     - stage: Test
#       name: freecadcmd-tryout
#       script:
#         - sudo add-apt-repository -y ppa:freecad-maintainers/freecad-stable
#         - sudo apt-get update
#         - sudo apt-get install -y freecad freecad-python3

#         - which freecad
#         - which freecadcmd

#         - cd freecadcmd-tryout/helloworld
#         - freecadcmd ./helloworld.py
#         - cd -

#         - cd freecadcmd-tryout/take-screen-shot
#         - freecadcmd ./helloworld.py
#         - freecad ./take_screenshot.py
#         - cd -

dist: xenial
services:
  - xvfb

jobs:
  include:
    - stage: Test
      name: freecadcmd-tryout, take-screen-shot

      # running freecad requires GUI
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start

      script:
        - echo 'helloworld'

        - sudo add-apt-repository -y ppa:freecad-maintainers/freecad-stable
        - sudo apt-get update
        - sudo apt-get install -y freecad freecad-python3

        - which freecad
        - which freecadcmd

        - cd freecadcmd-tryout/helloworld
        -   freecadcmd ./helloworld.py
        - cd -

        # NOTE: resume this test as requires GUI, currently running on travis and i dunno how to do.
        - cd freecadcmd-tryout/take-screen-shot
        -   freecadcmd ./helloworld.py
        -   freecadcmd ./take_screenshot.py
        -   ls -l screencapture/test-screenshot0.jpg
        -   ls -l screencapture/test-screenshot1.jpg
        -   ls -l screencapture/test-screenshot2.jpg
        - cd -

      after_failure:
        - cat $HOME/.FreeCAD/FreeCAD.log