# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/environment-variables/
# https://docs.travis-ci.com/user/job-lifecycle/

# You can import up to 25 other configs in total.
os: linux

jobs:
  include:
    - stage: Test
      name: freecadcmd-tryout
      script:
        - sudo add-apt-repository -y ppa:freecad-maintainers/freecad-stable
        - sudo apt-get update
        - sudo apt-get install -y freecad freecad-python3

        - which freecad
        - which freecadcmd

        - cd freecadcmd-tryout/helloworld
        - freecadcmd ./helloworld.py
        - cd -
